[firebase_client]
"apiKey" ="AIzaSyDq5QJPfTnG6vuQK9jSizaIsjlD0jc4OUY"
"authDomain"= "streamlit-ct-bfba3.firebaseapp.com"
"projectId"= "streamlit-ct-bfba3"
"databaseURL" ="https://streamlit-ct-bfba3-default-rtdb.asia-southeast1.firebasedatabase.app"
"storageBucket" = "streamlit-ct-bfba3.firebasestorage.app"
"messagingSenderId" = "646078078307"
"appId"= "1=646078078307:web:a1e94d7dc2b661b4410756"
"measurementId"= "G-95S5KFNXDC"

[firebase_admin]
"type" = "service_account"
"project_id"= "streamlit-ct-bfba3"
"private_key_id"= "441d855b31b148a55c4ecd643e8213a37ac18a94"
"private_key"= "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDJirujS3PfYGIf\nEI3sX3ht5t1ILG6mkBS4soCoqoZ/gm8Iq0MjFCaZ0Lt2cw/dKIXou0mCH74gz2gu\nfZqdqBIrQvbWDdTX1FfScGkBnzyiwn/zNBnzCp2mqMFlq73Mzaky/ZCAJiIz8CFW\nyAHO10QW7ugA77UrSkXsDQ/0HAFELWqf/+wozyhAqe3RfxO5fpCynG90sLtgha6e\n6oCa51ceObAj2wR1Ym5lxBNl9fzzvAXxdJOuvo3nYsYCfA38ah2LyUvH8U81cZwC\nGc2JD4ciUP3TTb8BVNWPLr2iyE5ePhjb+v96Ol1NaSDxnKqEg1IjekBc8vmXvOPX\nTR16u/FVAgMBAAECggEABO0PpgTyREDvqlu2Dv4htun1eaNLDGYpeNQ1bH9H10us\nWWq6MtwguhIN1ZjSsptKyUPz9CrAyRODXojdDm0XuJf5Ptp1W9XJqbqWo8lXwDtU\nc5t6kOQEXhjyKoEr8UVg6n6jxAYVQENmb9+775QiYBR0djq6/l+2iCJPmViqjUHV\nxVeWT4VfNoH0WSaAyyTwEHUWXWk2sLnNwrSpoBLewKdz6jnpONJP9ia1ZaOxjnRH\nspwYtY0Hxzw6gAI+aDYLTyEoloN3AhR0BnKOkBLNB1qEtzbxDtMXJ4BtDDsmy/Jt\nKhN3FHoRJ9E2/yjz3mLxZrUs/fAxKzBpLI2+d8tD0QKBgQD47i+lyA0ALZ9utQqN\ngJPD5jLMWLn+XXkasja7a80sluBp7ntYT/qNCABM2oL97omYxvWxBuVZm9ybKTWH\nNgmN8J+S2kYeBAgxbYYpZi+0p0w16MRwKLq3/KF0qo+T8Om0tJiW7MBee2mRu3UQ\nRXQqz/A6afEGqefFEf6GiCPcHQKBgQDPRAPzhbNBlZx8UwDMmR3a02ucKE95SS7c\nWMcAfdbiZObqC6LUmIxhQJIr3cRda/xAOMdkKeauzjMvT/QuUs+M8P1kRyGPSpbQ\nbR2PvR6PhOt3K+BWhy2hPzHPARYR9t6kREOQwYAFSOVn49SZhrbBa0J5KLQMOck8\nV6+KsF20mQKBgQCiVxOT1idEWnyDQmYjahrzwwiV47dIf8Ue9+Jh0Cf6UFsCOpkO\nOvp3RySK+mY7HHl3vSk1zf18tvzj47gY+dC5VJd8ugTIRnDhaz/3d8Dc284Dyk1x\np949ZvAUmbcRECgZxT1OEBBUjb+HXu01M1ZTJVDRh428fsm758RKEDbysQKBgF0k\n59GsqB41KhoFAzrvJKeOk7Gdu/l5lgGYM/ZYlxUu20ca65Y25/9ckVP9WZ3SRY5m\n9dRhsDWmnQIKIGYg+P0R4A4MmVxX3ObV4o8SIoXE6jyoDy1TmoH4cF3i0xRHqU6R\nDvwiuXGmjNHfZU+JZuANX9YrIJ7N6U2g6ladY78hAoGBALrK9NqQikqBkUIg8udh\nsIpZCdM20GjOlAI4EZFHrLwD/hNUEm/4IHX3I5sQMvFBN6hiupVp/SgUUhGTFaBV\nnvsmKDDPwQwyc67M31biFs+ZqtrRI479Tt2gnko70/O+Hm8TM5gpW4bCRrVg02Kq\nEYm4HgavpuTxMDSq+Nnf+orN\n-----END PRIVATE KEY-----\n"
"client_email"= "firebase-adminsdk-fbsvc@streamlit-ct-bfba3.iam.gserviceaccount.com"
"client_id"= "115495741876875292685"
"auth_uri"= "https://accounts.google.com/o/oauth2/auth"
"token_uri"= "https://oauth2.googleapis.com/token"
"auth_provider_x509_cert_url"= "https://www.googleapis.com/oauth2/v1/certs"
"client_x509_cert_url"= "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40streamlit-ct-bfba3.iam.gserviceaccount.com"
"universe_domain"= "googleapis.com"

[firebase_login] 
"apiKey" = "AIzaSyDq5QJPfTnG6vuQK9jSizaIsjlD0jc4OUY" 
"authDomain" = "streamlit-ct-bfba3.firebaseapp.com"
"databaseURL" = "https://streamlit-ct-bfba3-default-rtdb.asia-southeast1.firebasedatabase.app"
"projectId" = "streamlit-ct-bfba3" 
"storageBucket" = "streamlit-ct-bfba3.firebasestorage.app"
"messagingSenderId" = "646078078307" 
"appId" = "1:646078078307:web:72b1a124961904a7410756" 
"measurementId" = "G-WDM88X13T6"

[llm_server] 
"url" = "http://127.0.0.1:11434"